version: '3.4'

services:
    api:
        image: ${DOCKER_REGISTRY-}api
        environment:
            - DATABASE=Data Source=ms-sql-server;Initial Catalog=LancheRapidoBD;Encrypt=false;User ID=SA;Password=Pa55w0rd2021;Trusted_Connection=False; TrustServerCertificate=True;
            - MERCADO_PAGO_BASE_URL=https://api.mercadopago.com
            - MERCADO_PAGO_CRIAR_QR_ORDER_PATH=/instore/orders/qr/seller/collectors/138070335/pos/SUC001POS001/qrs
            - MERCADO_PAGO_CONSULTAR_QR_ORDER_PATH=/merchant_orders/{0}
            - MERCADO_PAGO_AUTHORIZATION=Bearer TEST-4232857146985951-071622-d45bfa46f542e8096b143477cbc1d167-138070335
            - MERCADO_PAGO_SPONSOR_ID=149081155		
            - WEBHOOK_ENDPOINT=https://webhook.site/5ee91173-c184-4084-ac8a-66d527948ad5
        restart: always
        build:
          context: .
          dockerfile: Api/Dockerfile
        ports:
            - "5000:5000"
            - "5001:5001"
        depends_on:
            - ms-sql-server

    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Pa55w0rd2021"
          MSSQL_PID: Express
        ports:
          - "1433:1433"
        volumes:
            - ./data:/var/opt/mssql/data
            - ./log:/var/opt/mssql/log

networks:
  default:
    driver: bridge
