apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  DATABASE: "Data Source=sqlserver;Initial Catalog=LancheRapidoBD;User ID=SA;Password=YourStrong!Passw0rd;TrustServerCertificate=true"  